# Generated by Django 5.2.7 on 2025-10-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobdescription_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='created_by',
        ),
    ]
