# Generated by Django 5.2.7 on 2025-10-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='rank_score',
            new_name='final_score',
        ),
        migrations.AddField(
            model_name='ranking',
            name='education_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ranking',
            name='experience_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ranking',
            name='keyword_density_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ranking',
            name='missing_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ranking',
            name='resume_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ranking',
            name='skill_match_score',
            field=models.FloatField(default=0.0),
        ),
    ]
